on:
  push:
    tags:
      - '*'

name: Publish

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup .NET
        run:  dotnet workload install android ios maccatalyst macos
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: olegtarasov/get-tag@v2-release
        id: tag_name
      - name: Build and pack
        run: |
          $suffix = "${{ steps.tag_name.outputs.tag }}" -replace "^[^\-]+-?", ""
          dotnet pack -c Release -o . --version-suffix "$suffix" FluentIcons.Common/FluentIcons.Common.csproj
          dotnet pack -c Release -o . --version-suffix "$suffix" FluentIcons.Avalonia/FluentIcons.Avalonia.csproj
          dotnet pack -c Release -o . --version-suffix "$suffix" FluentIcons.Avalonia.Fluent/FluentIcons.Avalonia.Fluent.csproj
          dotnet pack -c Release -o . --version-suffix "$suffix" FluentIcons.Maui/FluentIcons.Maui.csproj
          dotnet pack -c Release -o . --version-suffix "$suffix" FluentIcons.WinUI/FluentIcons.WinUI.csproj
          dotnet pack -c Release -o . --version-suffix "$suffix" FluentIcons.WPF/FluentIcons.WPF.csproj
      - name: Publish
        run: |
          dotnet nuget push FluentIcons.*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
