on:
  push:
    tags:
      - '*'

name: Publish

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup .NET
        run:  dotnet workload install android ios maccatalyst
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build and pack
        run: |
          dotnet pack -c Release -o . FluentIcons.Common/FluentIcons.Common.csproj
          dotnet pack -c Release -o . FluentIcons.Avalonia/FluentIcons.Avalonia.csproj
          dotnet pack -c Release -o . FluentIcons.Avalonia.Fluent/FluentIcons.Avalonia.Fluent.csproj
          dotnet pack -c Release -o . FluentIcons.WinUI/FluentIcons.WinUI.csproj
          dotnet pack -c Release -o . FluentIcons.WPF/FluentIcons.WPF.csproj
      - name: Publish
        run: |
          dotnet nuget push FluentIcons.*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
