on:
  push:
    tags:
      - '*'

name: Release

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish Common
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: FluentIcons.Common/FluentIcons.Common.csproj
          VERSION_REGEX: <VersionPrefix>(.*)<\/VersionPrefix>
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      - name: Publish Avalonia
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: FluentIcons.Avalonia/FluentIcons.Avalonia.csproj
          VERSION_REGEX: <VersionPrefix>(.*)<\/VersionPrefix>
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
      - name: Publish WPF
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: FluentIcons.WPF/FluentIcons.WPF.csproj
          VERSION_REGEX: <VersionPrefix>(.*)<\/VersionPrefix>
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
