on:
  schedule:
    - cron: '42 0 * * *'
  workflow_dispatch:

name: Update

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    name: Update
    runs-on: windows-latest
    steps:
      - name: Set variables
        id: vars
        run: |
          echo "dotnet_version=$(dotnet --version)" >> $env:GITHUB_OUTPUT
          echo "program_data=$env:ProgramData" >> $env:GITHUB_OUTPUT
      - name: Restore cache
        id: restore
        uses: actions/cache/restore@v4
        with:
          key: ${{ steps.vars.outputs.dotnet_version }}
          path: ${{ steps.vars.outputs.program_data }}\dotnet\workloads
      - name: Setup .NET workloads
        if: ${{ ! steps.restore.outputs.cache-hit }}
        run: dotnet workload install android ios maccatalyst macos
      - name: Save cache
        if: ${{ ! steps.restore.outputs.cache-hit }}
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.vars.outputs.dotnet_version }}
          path: ${{ steps.vars.outputs.program_data }}\dotnet\workloads
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 16
          fetch-tags: true
          submodules: true
          token: ${{ secrets.TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - cwd: seagull-icons
      - name: Setup Python packages
        run: pip install fonttools PyYAML
      - name: Update
        run: ./update.ps1
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          tags: true
